# Generated by Django 5.0.6 on 2024-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0002_cart_cartitem_category_product_delete_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
