# Generated by Django 5.0.6 on 2024-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0003_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='portion_size',
            field=models.CharField(default='Small', max_length=50),
        ),
    ]
