# Generated by Django 5.0.6 on 2024-06-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0010_alter_order_created_at_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sungrilla.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sungrilla.product')),
            ],
        ),
    ]
