# Generated by Django 5.0.6 on 2024-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0011_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
