# Generated by Django 5.0.6 on 2024-06-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0013_cart_paid_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
