# Generated by Django 5.0.6 on 2024-06-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0018_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
