# Generated by Django 5.0.6 on 2024-07-08 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungrilla', '0026_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 10, 27, 38, 268012)),
        ),
    ]
